#ifndef __n25q256_commands__
#define __n25q256_commands__


//
// Register Bit definitions
//

// STATUS Register
#define SR_STATUS_WRITE_ENABLE     ( 1 << 7 )
#define SR_MEM_PROTECT_TOP_BOTTOM  ( 1 << 6 )
#define SR_BLOCK_PROTECT_3         ( 1 << 6 )
#define SR_BLOCK_PROTECT_2         ( 1 << 4 )
#define SR_BLOCK_PROTECT_1         ( 1 << 3 )
#define SR_BLOCK_PROTECT_0         ( 1 << 2 )
#define SR_WRITE_ENABLE_LATCH      ( 1 << 1 )
#define SR_WRITE_IN_PROGRESS       ( 1 << 0 )

// Non-Volatile configuration Register
#define NV_DUMMY_CLOCKS_0000
#define NV_DUMMY_CLOCKS_0001
// not required
#define NV_DUMMY_CLOCKS_1111

#define NV_128MB_SEGMENT_SELECT    ( 1 << 1 )
#define NV_3BYTE_ADDRESS_ENABLE    ( 1 << 0 )


//FLag status register
#define FLAG_STATUS_ACTIVE         ( 1 << 7 )
#define FLAG_ERASE_SUSPEND         ( 1 << 6 )
#define FLAG_ERASE_ERROR           ( 1 << 5 )
#define FLAG_PROGRAM_ERROR         ( 1 << 4 )
#define FLAG_VPP_ERROR             ( 1 << 3 )
#define FLAG_PROGRAM_SUSPEND       ( 1 << 2 )
#define FLAG_PROTECT_ERROR         ( 1 << 1 )
#define FLAG_ADDRESS_MODE          ( 1 << 0 )



//
// COMMAND SET
//

#define CMD_RESET_ENABLE        0x66
#define CMD_RESET_MEMORY        0x99

#define CMD_READ_ID             0x9E
#define CMD_MULTIPLE_IO_READ_ID 0xAF
#define CMD_RAD_SERIAL_FLASH_DISCOVERY_PARAMETER 0x5A

#define CMD_READ 0x03
#define CMD_FAST_READ 0x0B
#define CMD_DUAL_OUTPUT_FAST_READ 0x3B
#define CMD_DUAL_INPUT_OPUTPUT_FAST_READ
#define CMD_QUAD_OUTPUT_FAST_READ

#define CMD_FAST_READ_DTR 0x0D
#define CMD_DUAL_OUTPUT_FAST_READ_DTR
#define CMD_QUAD_OUTPUT_FAST_READ_DTR
#define CMD_QUAD_INPUT_OUTPUT_FAST_READ_DTR

#define CMD_4_BYTE_READ 0x13
#define CMD_4_BYTE_FAST_READ 0x3C
#define CMD_4_BYTE_DUAL_OUTPUT_FAST_READ
#define CMD_4_BYTE_DUAL_INPUT_OUTPUT_FAST_READ

#define CMD_WRITE_ENABLE 0x06
#define CMD_WRITE_DISABLE 0x04

#define CMD_READ_STATUS_REGISTER 0x05
#define CMD_WRITE_STATUS_REGISTER 0x01
#define CMD_READ_LOCK_REGISTER 0xE8
#define CMD_WRITE_LOCK_REGISTER 0xE5
#define CMD_READ_FLAG_STATUS_REGISTER 0x70
#define CMD_CLEAR_FLAG_STATUS_REGISTER 0x50
#define CMD_READ_NONVOLATILE_CONFIG_REGISTER 0xB5
#define CMD_WRITE_NONVOLATILE_CONFIG_REGISTER 0xB1
#define CMD_READ_VOLATILE_CONFIG_REGISTER 0x85
#define CMD_WRITE_VOLATILE_CONFIG_REGISTER 0x81

#define CMD_READ_ENHANCED_VOLATILE_CONFIG_REGISTER 0x65
#define CMD_WRITE_ENHANCED_VOLATILE_CONFIG_REGISTER 0x61
#define CMD_READ_EXTENDED_ADDRESS_REGISTER 0xC8
#define CMD_WRITE_EXTENDED_ADDRESS_REGISTER 0xC5

#define CMD_PAGE_PROGRAM 0x02
#define CMD_4_BYTE_PAGE_PROGRAM 0x12
#define CMD_DUAL_INPUT_FAST_PROGRAM 0xA2
#define CMD_EXTENDED_DUAL_INPUT_FAST_PROGRAM 0x02
#define CMD_QUAD_INPUT_FAST_PROGRAM 0x32
#define CMD_4_BYTE_QUAD_INPUT_FAST_PROGRAM 0x34
#define CMD_EXTENDED_QUAD_INPUT_FAST_PROGRAM 0x02

#define CMD_SUBSECTOR_ERASE 0x20
#define CMD_4_BYTE_SUBSECTOR_ERASE 0x21
#define CMD_SECTOR_ERASE 0xD8
#define CMD_4_BYTE_SECTOR_ERASE 0xDC
#define CMD_BULK_ERASE 0xc7
#define CMD_PROGRAM_ERASE_RESUME 0x7A
#define CMD_PROGRAM_ERASE_SUSPEND 0x75

#define CMD_READ_OTP_ARRAY 0x4B
#define CMD_PROGRAM_OTP_ARRAY 0x42

#define CMD_ENTER_4_BYTE_ADDRESS_MODE 0xB7
#define CMD_EXIT_4_BYTE_ADDRESS_MODE 0xE9

#define CMD_ENTER_QUAD
#define CMD_EXIT_QUAD

#define CMD_ENTER_DEEP_POWER_DOWN 0xB9
#define CMD_RELEASE_DEEP_POWER_DOWN 0xAB



#endif /* __n25q256_commands__ */
